export const fnsDepartmentMasterSeed = [
  {
    id: 1,
    code: "BIO",
    name: "ພາກວິຊາ ຊີວະວິທະຍາ",
    nameEn: "Biology",
    isActive: true,
  },
  {
    id: 2,
    code: "CHEM",
    name: "ພາກວິຊາ ເຄມີສາດ",
    nameEn: "Chemistry",
    isActive: true,
  },
  {
    id: 3,
    code: "PHYS",
    name: "ພາກວິຊາ ຟີຊິກສາດ",
    nameEn: "Physics",
    isActive: true,
  },
  {
    id: 4,
    code: "MATH",
    name: "ພາກວິຊາ ຄະນິດສາດ ແລະ ສະຖິຕິ",
    nameEn: "Mathematics and Statistics",
    isActive: true,
  },
  {
    id: 5,
    code: "CS",
    name: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    nameEn: "Computer Science",
    isActive: true,
  },
];

export { fnsLocationMasterSeed } from "./locationMasterData.js";
export const fnsAuthMembers = [
  {
    id: 1,
    role: "teacher",
    username: "teacher01",
    password: "123456",
    studentCode: "",
    employeeCode: "T001",
    firstName: "ອາຈານ",
    lastName: "ຫ້ອງຄຸ້ມຄອງ",
    fullName: "ອາຈານ ຫ້ອງຄຸ້ມຄອງ",
    email: "fns@nuol.edu.la",
    phone: "021 770173",
    department: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    identityStatus: "verified",
    cardImageUrl: "",
  },
  {
    id: 2,
    role: "student",
    username: "student01",
    password: "123456",
    studentCode: "66000001",
    employeeCode: "",
    firstName: "ນັກສຶກສາ",
    lastName: "ຕົວຢ່າງ",
    fullName: "ນັກສຶກສາ ຕົວຢ່າງ",
    email: "student01@example.com",
    phone: "020-3333-4444",
    department: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    identityStatus: "verified",
    cardImageUrl: "student-card-sample.jpg",
  },
];
