export const fnsDepartmentMasterSeed = [
  {
    id: 1,
    code: "BIO",
    name: "ພາກວິຊາ ຊີວະວິທະຍາ",
    nameEn: "Biology",
    isActive: true,
  },
  {
    id: 2,
    code: "CHEM",
    name: "ພາກວິຊາ ເຄມີສາດ",
    nameEn: "Chemistry",
    isActive: true,
  },
  {
    id: 3,
    code: "PHYS",
    name: "ພາກວິຊາ ຟີຊິກສາດ",
    nameEn: "Physics",
    isActive: true,
  },
  {
    id: 4,
    code: "MATH",
    name: "ພາກວິຊາ ຄະນິດສາດ ແລະ ສະຖິຕິ",
    nameEn: "Mathematics and Statistics",
    isActive: true,
  },
  {
    id: 5,
    code: "CS",
    name: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    nameEn: "Computer Science",
    isActive: true,
  },
];

export const fnsLocationMasterSeed = [
  {
    id: 1,
    name: "ຫ້ອງຄຸ້ມຄອງ",
    building: "ຄະນະວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "handover",
    detail: "ຈຸດຮັບຝາກ ແລະ ສົ່ງມອບສິ່ງຂອງ",
    isActive: true,
  },
  {
    id: 2,
    name: "ລານກາງຄະນະ",
    building: "ຄະນະວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ພື້ນທີ່ກາງແຈ້ງ ແລະ ຈຸດນັ່ງພັກ",
    isActive: true,
  },
  {
    id: 3,
    name: "BI106 - ຫ້ອງ Media",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງ Media",
    isActive: true,
  },
  {
    id: 4,
    name: "BI107 - ຫ້ອງປະຕິບັດການ",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງປະຕິບັດການ",
    isActive: true,
  },
  {
    id: 5,
    name: "BI108 - ຫ້ອງຮຽນ",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 6,
    name: "BI109 - ຫ້ອງຮຽນ",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 7,
    name: "BI110 - ຫ້ອງຮຽນ",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 8,
    name: "BI111 - ຫ້ອງຮຽນ",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 9,
    name: "BI112 - SIC Samsung Innovation Campus",
    building: "ຕຶກ BI ຕຶກທົດລອງ",
    floor: "",
    locationType: "both",
    detail: "SIC Samsung Innovation Campus",
    isActive: true,
  },
  {
    id: 10,
    name: "CH - ຫ້ອງທົດລອງພາກເຄມີ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງທົດລອງພາກເຄມີ",
    isActive: true,
  },
  {
    id: 11,
    name: "CH100 - ຫ້ອງພັກຄູ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງພັກຄູ",
    isActive: true,
  },
  {
    id: 12,
    name: "CH101 - ພາກວິຊາເຄມີສາດ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ພາກວິຊາເຄມີສາດ",
    isActive: true,
  },
  {
    id: 13,
    name: "CH102 - ຫ້ອງຮຽນ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 14,
    name: "CH103 - ຫ້ອງທົດລອງເປົ່າແກ້ວ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງທົດລອງເປົ່າແກ້ວ",
    isActive: true,
  },
  {
    id: 15,
    name: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    building: "ອາຄານຫ້ອງທົດລອງວິທະຍາສາດທຳມະຊາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    isActive: true,
  },
  {
    id: 16,
    name: "PH101 - ຫ້ອງພັກຄູ",
    building: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງພັກຄູ",
    isActive: true,
  },
  {
    id: 17,
    name: "PH102 - ຫ້ອງຮຽນ",
    building: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 18,
    name: "PH103 - ຫ້ອງພັກຄູ",
    building: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງພັກຄູ",
    isActive: true,
  },
  {
    id: 19,
    name: "PH104 - ຫ້ອງຮຽນ",
    building: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 20,
    name: "PH105 - ຫ້ອງຮຽນ",
    building: "ຫ້ອງທົດລອງ ຟີຊິກສາດ",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 21,
    name: "CS001 - ຫ້ອງຮຽນ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 22,
    name: "CS002 - ຫ້ອງພັກຄູ + ຫ້ອງອາຈານ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງພັກຄູ + ຫ້ອງອາຈານ",
    isActive: true,
  },
  {
    id: 23,
    name: "CS003 - ຫ້ອງຮຽນ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 24,
    name: "CS004 - ຫ້ອງພັກຄູ + ຫ້ອງອາຈານ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງພັກຄູ + ຫ້ອງອາຈານ",
    isActive: true,
  },
  {
    id: 25,
    name: "CS005 - ຫ້ອງຮຽນ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 26,
    name: "CS006 - ຫ້ອງ Robot",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງ Robot",
    isActive: true,
  },
  {
    id: 27,
    name: "CS007 - ຫ້ອງຮຽນ",
    building: "ຕຶກ CS",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 28,
    name: "MA101 - ຫ້ອງສະໝຸດ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງສະໝຸດ",
    isActive: true,
  },
  {
    id: 29,
    name: "MA102 - ຫ້ອງການສະມາຄົມ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງການສະມາຄົມ",
    isActive: true,
  },
  {
    id: 30,
    name: "MA103 - ຫ້ອງຮຽນ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 31,
    name: "MA104 - ຫ້ອງຮຽນ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຮຽນ",
    isActive: true,
  },
  {
    id: 32,
    name: "MA105 - ຫ້ອງຮຽນ / ຫ້ອງອາຈານ + ຫ້ອງພັກຄູ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຂໍ້ມູນຫ້ອງ MA105 ລະບຸທັງຫ້ອງຮຽນ ແລະ ຫ້ອງອາຈານ + ຫ້ອງພັກຄູ",
    isActive: true,
  },
  {
    id: 33,
    name: "MA106 - ຫ້ອງຫົວໜ້າໜ່ວຍ + ຫ້ອງອາຈານ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຫົວໜ້າໜ່ວຍ + ຫ້ອງອາຈານ",
    isActive: true,
  },
  {
    id: 34,
    name: "MA107 - ຫ້ອງຄະນະພາກ + ຫ້ອງອາຈານ",
    building: "ຕຶກ MA",
    floor: "",
    locationType: "both",
    detail: "ຫ້ອງຄະນະພາກ + ຫ້ອງອາຈານ",
    isActive: true,
  },
];

export const fnsAuthMembers = [
  {
    id: 1,
    role: "teacher",
    username: "teacher01",
    password: "123456",
    studentCode: "",
    employeeCode: "T001",
    firstName: "ອາຈານ",
    lastName: "ຫ້ອງຄຸ້ມຄອງ",
    fullName: "ອາຈານ ຫ້ອງຄຸ້ມຄອງ",
    email: "fns@nuol.edu.la",
    phone: "021 770173",
    department: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    identityStatus: "verified",
    cardImageUrl: "",
  },
  {
    id: 2,
    role: "student",
    username: "student01",
    password: "123456",
    studentCode: "66000001",
    employeeCode: "",
    firstName: "ນັກສຶກສາ",
    lastName: "ຕົວຢ່າງ",
    fullName: "ນັກສຶກສາ ຕົວຢ່າງ",
    email: "student01@example.com",
    phone: "020-3333-4444",
    department: "ພາກວິຊາ ວິທະຍາສາດຄອມພິວເຕີ",
    identityStatus: "verified",
    cardImageUrl: "student-card-sample.jpg",
  },
];
